--- #YAML:1.0
name:                Devel-Mortality
version:             0.01
abstract:            Helper functions for XS developers debugging mortality issues
license:             mit
author:              
    - Claes Jakobsson <claesjac@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    File::Basename:                0
    File::Spec:                    0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
